# flake8: noqa

# -*- coding: utf-8 -*-
"""LA NC Geo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCCHZDS2udKXlePIgezV_9cKQsRG681h
"""

from os.path import join, dirname
import glob

import geopandas

DATA_FOLDER = join(dirname(__file__), 'data')
list_of_files = glob.glob(join(DATA_FOLDER, "nc-boundary-geojson-*.json"))

NEWER_DATA_FILE = max(list_of_files)
OLDER_DATA_FILE = min(list_of_files)

with open(NEWER_DATA_FILE, "r") as read_file:
    new_df = geopandas.read_file(read_file)

    with open(OLDER_DATA_FILE, "r") as read_file:
        old_df = geopandas.read_file(read_file)

        print(new_df)
        print(old_df)
