export default {
  YEARS: [
    '2015',
    '2016',
    '2017',
    '2018',
    '2019',
  ],
  MONTHS: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  REQUESTS: [
    'Bulky Items',
    'Dead Animal Removal',
    'Electronic Waste',
    'Graffiti Removal',
    'Homeless Encampment',
    'Illegal Dumping Pickup',
    'Metal/Household Appliances',
    'Single Streetlight Issue',
    'Multiple Streetlight Issue',
    'Report Water Waste',
    'Other',
  ],
};
