export default {};

export const YEARS = [
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
];

export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const REQUEST_TYPES = [
  {
    type: 'Bulky Items',
    abbrev: 'BLK',
    color: '#FF0000',
  },
  {
    type: 'Dead Animal',
    abbrev: 'DAN',
    color: '#4FEFEF',
  },
  {
    type: 'E-Waste',
    abbrev: 'EWT',
    color: '#DDEC9F',
  },
  {
    type: 'Graffiti',
    abbrev: 'GFT',
    color: '#2368D0',
  },
  {
    type: 'Homeless Encampment',
    abbrev: 'HLE',
    color: '#ECB800',
  },
  {
    type: 'Illegal Dumping',
    abbrev: 'ILD',
    color: '#6A8011',
  },
  {
    type: 'Metal/Household Appliances',
    abbrev: 'MHA',
    color: '#B8D0FF',
  },
  {
    type: 'Single Streetlight',
    abbrev: 'SSL',
    color: '#AD7B56',
  },
  {
    type: 'Multiple Streetlight',
    abbrev: 'MSL',
    color: '#F7ADAD',
  },
  {
    type: 'Feedback',
    abbrev: 'FBK',
    color: '#FFE6B7',
  },
  {
    type: 'Other',
    abbrev: 'OTH',
    color: '#6D7C93',
  },

  /*
   * Is 'Report Water Waste' still a valid request type?
   * If so, we're missing it on the front end mockups.
   */
];

export const REQUESTS = [
  'Bulky Items',
  'Dead Animal Removal',
  'Electronic Waste',
  'Graffiti Removal',
  'Homeless Encampment',
  'Illegal Dumping Pickup',
  'Metal/Household Appliances',
  'Single Streetlight Issue',
  'Multiple Streetlight Issue',
  'Report Water Waste',
  'Other',
];

export const COUNCILS = [
  'ARLETA NC',
  'ARROYO SECO NC',
  'ATWATER VILLAGE NC',
  'BEL AIR-BEVERLY CREST NC',
  'BOYLE HEIGHTS NC',
  'BRENTWOOD CC',
  'CANOGA PARK NC',
  'CENTRAL ALAMEDA NC',
  'CENTRAL HOLLYWOOD NC',
  'CENTRAL SAN PEDRO NC',
  'CHATSWORTH NC',
  'COASTAL SAN PEDRO NC',
  'COMMUNITY AND NEIGHBORS FOR NINTH DISTRICT UNITY (CANNDU)',
  'DEL REY NC',
  'DOWNTOWN LOS ANGELES',
  'EAGLE ROCK NC',
  'EAST HOLLYWOOD NC',
  'ECHO PARK NC',
  'ELYSIAN VALLEY RIVERSIDE NC',
  'EMPOWERMENT CONGRESS CENTRAL AREA NDC',
  'EMPOWERMENT CONGRESS NORTH AREA NDC',
  'EMPOWERMENT CONGRESS SOUTHEAST AREA NDC',
  'EMPOWERMENT CONGRESS SOUTHWEST AREA NDC',
  'EMPOWERMENT CONGRESS WEST AREA NDC',
  'ENCINO NC',
  'FOOTHILL TRAILS DISTRICT NC',
  'GLASSELL PARK NC',
  'GRANADA HILLS NORTH NC',
  'GRANADA HILLS SOUTH NC',
  'GREATER CYPRESS PARK NC',
  'GREATER ECHO PARK ELYSIAN NC',
  'GREATER TOLUCA LAKE NC',
  'GREATER VALLEY GLEN COUNCIL',
  'GREATER WILSHIRE NC',
  'HARBOR CITY NC',
  'HARBOR GATEWAY NORTH NC',
  'HARBOR GATEWAY SOUTH NC',
  'HERMON NC',
  'HISTORIC CULTURAL NC',
  'HISTORIC CULTURAL NORTH NC',
  'HISTORIC HIGHLAND PARK NC',
  'HOLLYWOOD HILLS WEST NC',
  'HOLLYWOOD STUDIO DISTRICT NC',
  'HOLLYWOOD UNITED NC',
  'LA-32 NC',
  'LAKE BALBOA NC',
  'LINCOLN HEIGHTS NC',
  'LOS FELIZ NC',
  'MACARTHUR PARK NC',
  'MAR VISTA CC',
  'MID CITY NC',
  'MID CITY WEST CC',
  'MID-TOWN NORTH HOLLYWOOD NC',
  'MISSION HILLS NC',
  'NC VALLEY VILLAGE',
  'NC WESTCHESTER/PLAYA',
  'NOHO NC',
  'NOHO WEST NC',
  'NORTH HILLS EAST',
  'NORTH HILLS WEST NC',
  'NORTH HOLLYWOOD NORTHEAST NC',
  'NORTH WESTWOOD NC',
  'NORTHRIDGE EAST',
  'NORTHRIDGE SOUTH NC',
  'NORTHRIDGE WEST',
  'NORTHWEST SAN PEDRO NC',
  'OLYMPIC PARK NC',
  'P.I.C.O. NC',
  'PACIFIC PALISADES NC',
  'PACOIMA NC',
  'PALMS NC',
  'PANORAMA CITY NC',
  'PARK MESA HEIGHTS CC',
  'PICO UNION NC',
  'PORTER RANCH NC',
  'RAMPART VILLAGE NC',
  'RESEDA NC',
  'SHERMAN OAKS NC',
  'SILVER LAKE NC',
  'SOUTH CENTRAL NC',
  'SOUTH ROBERTSON NC',
  'STUDIO CITY NC',
  'SUN VALLEY AREA NC',
  'SUNLAND-TUJUNGA NC',
  'SYLMAR NC',
  'TARZANA NC',
  'UNITED NEIGHBORHOODS OF THE HISTORIC ARLINGTON HEIGHTS, WEST ADAMS, AND JEFFERSON PARK COMMUNITY',
  'VAN NUYS NC',
  'VENICE NC',
  'VOICES OF 90037',
  'WATTS NC',
  'WEST ADAMS NC',
  'WEST HILLS NC',
  'WEST LOS ANGELES NC',
  'WESTLAKE NORTH NC',
  'WESTLAKE SOUTH NC',
  'WESTSIDE NC',
  'WESTWOOD NC',
  'WILMINGTON NC',
  'WILSHIRE CENTER - KOREATOWN NC',
  'WINNETKA NC',
  'WOODLAND HILLS-WARNER CENTER NC',
  'ZAPATA KING NC',
];
