name: Deploy_Frontend_Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  deploy_frontend_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Rebuild sass
      run: npm rebuild node-sass
    - name: Install Packages
      run: npm install
    - name: Setup environment
      run: |
        echo VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }} > .env
        echo MAPBOX_STREETS_URL=${{ secrets.MAPBOX_STREETS_URL }} >> .env
        echo MAPBOX_SATELLITE_URL=${{ secrets.MAPBOX_SATELLITE_URL }} >> .env
        echo API_URL=${{ secrets.API_URL_DEV }} >> .env
        echo REPORT_URL=${{ secrets.REPORT_URL }} >> .env
        echo SENTRY_CLIENT_DSN=${{ secrets.SENTRY_CLIENT_DSN }} >> .env
        echo MIXPANEL_ENABLED=${{ secrets.MIXPANEL_ENABLED }} >> .env
        echo MIXPANEL_TOKEN_PROD=${{ secrets.MIXPANEL_TOKEN_PROD }} >> .env
        echo MIXPANEL_TOKEN_DEV=${{ secrets.MIXPANEL_TOKEN_DEV }} >> .env
        echo VITE_CONTENTFUL_SPACE=${{ secrets.VITE_CONTENTFUL_SPACE }} >> .env
        echo VITE_CONTENTFUL_TOKEN=${{ secrets.VITE_CONTENTFUL_TOKEN }} >> .env
        echo GITHUB_SHA=${{ github.sha }} >> .env
    - name: Build project
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sync Development Build To S3
      run: |
        aws s3 sync dist s3://${{ secrets.S3_BUCKET_DEV }} --follow-symlinks --delete
    - name: Invalidate Cloudfront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_DEV }} --paths "/*"
